version: '2.4'

services:
  server:
    build: .
    image: "djetrl/backend:latest"
    ports:
      - "3003:80"
    depends_on: 
      - mongo

  mongo:
      image: mongo
      ports:
        - '27017:27017'